apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  selector:
    app: fleetman-position-simulator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
      - name: fleetman-position-simulator
        image: supinfo4kube/position-simulator:1.0.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
        ports:
        - containerPort: 8080
