apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: dlcardonag/fleetman-webapp
        ports:
        - containerPort: 80
